#!/bin/bash
set -e

NODE_VERSION="$(node --version 2>/dev/null || echo "none")"
if [[ "$NODE_VERSION" == "none" ]]; then
  echo "Installing Node.js"
  brew install node
fi

echo "System dependencies verified."
